# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learn-nbdev',
                'doc_host': 'https://nissan.github.io',
                'git_url': 'https://github.com/nissan/learn-nbdev',
                'lib_path': 'learn_nbdev'},
  'syms': {'learn_nbdev.core': {'learn_nbdev.core.foo': ('core.html#foo', 'learn_nbdev/core.py')}}}
